#!/usr/bin/env python3
"""Regenerate docs/campaign/<world>.md from the live manifests (run after any campaign data edit)."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
W = ['lawn','pool','night','desert','roof','frost','factory','moon']
def obj(l):
    return '; '.join(f"{o['type']}={o['target']}" for o in l['objectives']) or 'Clear waves'
for w in W:
    d = json.loads((root/f'data/campaign/{w}.json').read_text())
    out = [f"# {d['name']}", '', d['rule_text'], '', 'All 25 levels are mandatory; clear the previous world to unlock this world.',
           f"Balance revision: {d.get('balance_revision', 'v0.5')}. Generated by `tools/balance/write_world_guides.py` — do not hand-edit.", '',
           '| Level | Title | Scenario | Mode | Objectives | Waves | Spawns | Start sun | Blocked tiles | First-clear plant |', '|---|---|---|---|---|---:|---:|---:|---:|---|']
    for l in d['levels']:
        spawns = sum(len(x['spawns']) for x in l['wave_specs']); blocked = sum(r.count('#') for r in l['layout'])
        out.append(f"| {l['number']} | {l['title']} | {l['scenario']} | {l['mode']} | {obj(l)} | {len(l['wave_specs'])} | {spawns} | {l['start_sun']} | {blocked} | {l['reward_plant'] or '—'} |")
    (root/f'docs/campaign/{w}.md').write_text('\n'.join(out) + '\n')
print('wrote', len(W), 'world guides')
