class_name WorldArtConfig
extends Resource
## Data-driven battle art for one world (assets/art/worlds/<world>/world_art.tres).
## Generated by tools/art/build_all.py; hand-tweak values in the inspector.

## Full-screen 1920x1080 surround (house, fence, path). Never contains grass in the field.
@export var environment: Texture2D
## Playfield ground, exactly Board.board_rect() in size.
@export var ground: Texture2D
## Border overlay: board_rect grown by edge_margin (shadow, lip, overhanging blades).
@export var edge: Texture2D
@export var edge_margin: float = 40.0
## One strip per lane, drawn y-sorted just in front of that lane's feet line. May be empty.
@export var fringe: Array[Texture2D] = []
## Small clump drawn at walking zombies' feet (same row-sort as the fringe).
@export var tuft: Texture2D
## Strip top relative to the lane's feet line.
@export var fringe_offset_y: float = -20.0
@export var contact_shadow: Texture2D
@export var contact_shadow_color: Color = Color(1, 1, 1, 0.55)
## Offset of contact shadows from the feet (light comes from the top-left).
@export var contact_shadow_offset: Vector2 = Vector2(6, 4)
## Whole-scene light grade applied to the world (night, moon...). White = none.
@export var light_tint: Color = Color.WHITE
## UI accent for this world (map nodes, banners). The UI material set itself is shared.
@export var accent: Color = Color(0.5, 0.7, 0.29)
@export var ground_type: StringName = &"grass"
