# LEGACY (pre-v0.7) English string list. The maintained sources now live in
# tools/localization/src and are built by tools/localization/build_csv.py.
# Running this would wipe every translation, so it refuses unless --force is given.
import csv, os, sys
if "--force" not in sys.argv:
    sys.exit("tools/strings_en.py is legacy; use tools/localization/build_csv.py (pass --force to overwrite anyway).")
S = {
"GAME_TITLE": "Garden Defense",
"GAME_SUBTITLE": "Grow it. Graft it. Hold the lawn.",
"GAME_FOOTER": "Fan project · original art · v0.4 painted art & pools",
"UI_PLAY": "Play", "UI_ALMANAC": "Almanac", "UI_QUESTS": "Quest Log", "UI_SETTINGS": "Settings", "UI_QUIT": "Quit",
"UI_BACK": "Back", "UI_SHOP": "Shop", "UI_OPEN_SHOP": "Open shop", "UI_COINS": "{n} coins",
"UI_CONTINUE": "Continue", "UI_RETRY": "Try again", "UI_TO_MAP": "Back to map", "UI_RESUME": "Resume", "UI_RESTART": "Restart level",
"UI_DIFFICULTY": "Difficulty", "UI_COST": "Cost", "UI_RECHARGE": "Recharge", "UI_HP": "Health", "UI_ROLE": "Role",
"UI_TOUGHNESS": "Toughness", "UI_SPEED": "Speed",
"SPEED_SLOW": "slow", "SPEED_NORMAL": "normal", "SPEED_FAST": "fast",
"HUB_TITLE": "Choose a garden", "HUB_LOCKED": "Coming in a later update",
"MAP_LAWN_NAME": "Lawn", "MAP_POOL_NAME": "Poolside", "MAP_GRAVEYARD_NAME": "Night Graveyard", "MAP_BEACH_NAME": "Beach",
"MAP_ROOF_NAME": "Roof", "MAP_JUNGLE_NAME": "Night Jungle", "MAP_OASIS_NAME": "Oasis", "MAP_TUNDRA_NAME": "Tundra",
"MAP_BONUS": "Bonus", "MAP_LOCKED": "Locked. Clear a neighbouring node first.", "MAP_NEEDS_STARS": "Needs {n} stars.",
"MAP_GATE": "Star gate", "MAP_GATE_DESC": "Opens at {n} stars. You have {have}.",
"MAP_SHOP_DESC": "Spend coins on seed slots, starting sun, spare mowers and recipe hints.",
"MAP_REWARD_PLANT": "Reward: {name}", "MAP_REWARD_COINS": "Reward: {n} coins", "MAP_CLEARED": "Cleared ★", "MAP_BEST": "best: {name}",
"DIFFICULTY_STANDARD": "Standard", "DIFFICULTY_HARD": "Hard", "DIFFICULTY_HARD_PLUS": "Hard+",
"DIFF_DESC_STANDARD": "The intended experience.",
"DIFF_DESC_HARD": "15% more zombies, +15% bite damage, they take 10% less damage. Same speed and wave timing. Coins ×1.25.",
"DIFF_DESC_HARD_PLUS": "25% more zombies, +5% speed, +30% bite damage, they take 15% less damage, waves 5% closer. Coins ×1.5.",
"SEEDS_TITLE": "Pick your seeds", "SEEDS_SLOTS": "Slots {n}/{max}", "SEEDS_START": "Let's grow!",
"SEEDS_FIXED": "This level gives you a fixed set of seeds.", "SEEDS_HOVER_HINT": "Point at a seed to read about it.",
"SEEDS_ZOMBIES": "Expect:", "SEEDS_WAVES": "{n} waves",
"SEEDS_HYBRIDS_ALLOWED": "Grafting allowed: up to {n} hybrids. Both ingredients must be in your set.",
"SEEDS_HYBRIDS_BANNED": "No grafting on this level.",
"HUD_SHOVEL": "Shovel", "HUD_MENU": "Menu", "HUD_PAUSED": "Paused", "HUD_HYBRIDS": "Hybrids {n}/{max}",
"HUD_MOWER_KIT": "Repair mower ({n})", "HUD_HUGE_WAVE": "A big wave is coming!", "HUD_FINAL_WAVE": "Final wave!",
"HUD_GRAFT_INTO": "Graft → {name} ({cost})", "HUD_EVOLVE_INTO": "Evolve → {name} ({cost})",
"MSG_NOT_ENOUGH_SUN": "Not enough sun", "MSG_RECHARGING": "Seed is recharging", "MSG_CELL_OCCUPIED": "Something is already growing here",
"MSG_NO_RECIPE": "These two don't graft", "MSG_NOT_READY": "Let it grow a little first", "MSG_HYBRID_CAP": "Hybrid limit reached",
"MSG_GRAFT_DISABLED": "Grafting is not available here", "MSG_EVOLVE_LOCKED": "Evolving is not unlocked yet",
"MSG_NEEDS_RAFT": "Water: plant a Lily Raft here first",
"MAP_DIFFICULTY_READONLY": "Difficulty: {name}  (change it in Settings)",
"ALMANAC_GRAFT_COST": "{n} sun (seed + {fee} fee)", "ALMANAC_NOT_TRIED": "not tried yet",
"STAT_SUN": "{n} sun", "STAT_START_COOLDOWN": "First seed after", "STAT_MADE_BY": "Obtained by",
"STAT_GRAFT": "Graft only", "STAT_EVOLVE": "Evolution only", "STAT_SURFACE": "Grows on",
"STAT_LAWN": "Lawn (or a Lily Raft on water)", "STAT_WATER": "Water only",
"STAT_DAMAGE": "Damage per hit", "STAT_RATE": "Attack rate", "STAT_EVERY": "every {n} s", "STAT_DPS": "Damage per second",
"STAT_RANGE": "Range", "STAT_CELLS": "{n} cells", "STAT_WHOLE_LANE": "whole lane ahead", "STAT_PIERCE": "Pierces",
"STAT_ALL": "everything in line", "STAT_PROJECTILE": "Projectile speed", "STAT_SLOW": "Slow",
"STAT_SLOW_V": "-{p}% speed for {s} s", "STAT_AREA": "Blast radius", "STAT_BURN": "Burn", "STAT_BURN_V": "{d} dmg/s for {s} s",
"STAT_FREEZE": "Freeze", "STAT_CHAIN": "Chain", "STAT_CHAIN_V": "{n} jumps, {r} cells apart", "STAT_STUN": "Stun",
"STAT_THORNS": "Thorns", "STAT_PER_BITE": "{n} per bite", "STAT_PUSH": "Push back", "STAT_PULL": "Pull range",
"STAT_REGEN": "Regeneration", "STAT_REBIRTHS": "Rebirths", "STAT_SUN_MADE": "Sun production",
"STAT_SUN_V": "{n} every {s} s (~{m}/min)", "STAT_ARM": "Arming time", "STAT_CHEW": "Chewing time",
"STAT_BUFF": "Neighbour buff", "STAT_SUMMONS": "Max summons", "STAT_GROW_TIME": "Ready to graft after",
"STAT_LIMIT": "Board limit", "STAT_LIMIT_V": "{n} at a time", "STAT_EVOLVES": "Evolution", "STAT_RECIPE": "Recipe",
"STAT_GRAFTS_INTO": "Grafts into", "STAT_ARMOR": "Armour", "STAT_SPEED_V": "{c} cells/s ({p} px/s)",
"STAT_CROSS": "Time to cross the lawn", "STAT_BITE": "Bite", "STAT_BITE_V": "{d} every {s} s", "STAT_EAT_DPS": "Eating damage/s",
"STAT_THREAT": "Wave cost", "STAT_POD_HITS": "Pod Shooter hits to kill", "STAT_IMMUNE": "Immune to", "STAT_SIZE": "Size",
"ARMOR_CONE": "cone", "ARMOR_BUCKET": "bucket", "ARMOR_SHIELD": "shield", "ARMOR_HELMET": "helmet", "ARMOR_NONE": "none",
"IMMUNE_DEVOUR": "being swallowed", "IMMUNE_PUSH": "push-back", "IMMUNE_PULL": "pulling", "IMMUNE_FREEZE": "freezing",
"MSG_BAD_SURFACE": "This plant can't grow here",
"MSG_RECIPE_DISCOVERED": "New graft: {name}!", "MSG_HINT_GAINED": "Hint: try {a} + {b}", "MSG_COINS_GAINED": "+{n} coins", "MSG_QUEST_DONE": "Quest complete: {name}! Claim it in the Quest Log.",
"RESULT_WIN": "Lawn defended!", "RESULT_LOSE": "They got in…", "RESULT_LOSE_DESC": "A zombie reached the house. Rethink the weak lane and try again.",
"RESULT_STAR": "★ Star earned", "RESULT_COINS": "+{n} coins", "RESULT_NEW_PLANT": "New plant: {name}",
"FEATURE_GRAFT": "Grafting unlocked! Pick a different seed and drop it on a grown plant to merge them, if a recipe exists. Hybrids can't be planted directly.",
"FEATURE_EVOLVE": "Evolving unlocked! Drop a seed onto a grown plant of the same kind to upgrade it to the next tier.",
"HINT_LAWN_01": "Plant Sunbuds for sun, then Pod Shooters in front of them. Click falling sun to collect it.",
"HINT_LAWN_02": "Cone Heads wear armour. Keep two shooters on busy lanes.",
"HINT_LAWN_03": "Flags mark big waves. Save sun before they arrive.",
"HINT_LAWN_04": "Sprinters are fast but fragile. A Thorn Mine in their path works wonders.",
"HINT_LAWN_05": "Bucket Heads are tough. Slow them with Frost Mint and focus fire.",
"HINT_LAWN_06": "Grafting: drop a Frost Mint seed on a grown Pod Shooter. Hybrids are strong but limited.",
"HINT_LAWN_07": "Hurdlers vault over the first plant. Tall plants like Ironbark Wall stop the vault.",
"HINT_LAWN_08": "Shields stop shots from the front. Mines, Ember Berries, bees and Dandelion Puffs go around them.",
"HINT_LAWN_10": "Burrowers tunnel under everything and pop up by the house. Keep something behind your front line.",
"HINT_LAWN_12": "Brutes smash plants and can't be swallowed. Slow them early.",
"HINT_LAWN_BONUS_1": "Sprint Rush: fast zombies, short breaks, no grafting.",
"HINT_LAWN_BONUS_2": "Fixed Garden: make do with the seeds you're given.",
"HINT_LAWN_BONUS_3": "Pure Roots: base plants only. Prove they still hold up.",
"ALMANAC_PLANTS": "Plants", "ALMANAC_ZOMBIES": "Zombies", "ALMANAC_GRAFTS": "Grafts",
"ALMANAC_PICK": "Pick an entry on the left.", "ALMANAC_FEE": "fee +{n}", "ALMANAC_HINTED": "hinted",
"ALMANAC_FOUND": "Discovered {n} of {max} grafts.",
"ALMANAC_GRAFT_HELP": "Grafts cost the catalyst seed plus a fee. The base plant must be grown, and each level caps how many hybrids you can keep.",
"ALMANAC_EVOLVES": "Evolves into {name} (+{n} sun)", "ALMANAC_EVOLVED_FROM": "Evolved from {name}", "ALMANAC_RECIPE": "Graft: {a} + {b}",
"ROLE_PRODUCER": "producer", "ROLE_SHOOTER": "shooter", "ROLE_WALL": "wall", "ROLE_MINE": "mine", "ROLE_INSTANT": "instant",
"ROLE_SLOWER": "slower", "ROLE_TRAP": "trap", "ROLE_BLOCKER": "blocker", "ROLE_SUPPORT": "support", "ROLE_CONTROL": "control",
"ROLE_PIERCE": "pierce", "ROLE_SUMMONER": "summoner", "ROLE_AOE": "area",
"ROLE_FREEZE": "freezer", "ROLE_PLATFORM": "water platform", "ROLE_CHAIN": "chain lightning",
"RARITY_LEGENDARY": "Legendary", "ALMANAC_MAX_ON_BOARD": "Only {n} may grow on the lawn at a time.",
# v0.2 additions (previously only in the CSV)
"HUB_LAWN_TAG": "Classic campaign · 16 stages",
"HUB_POOL_TAG": "Poolside route · 7 stages",
"HUD_PAUSE": "Pause",
"HUD_SPEED": "Game speed",
"HUD_BASE_INTEGRITY": "Gate {n}/{max}",
"HUD_BREACH": "Breach! Gate integrity: {n}",
"HUD_WAVE_WARNING": "Big wave in {n}…",
"HINT_POOL_01": "Water cells need a Lily Raft first (it is added to your seeds for free). Plant on top of the raft.",
"HINT_POOL_02": "Lane pressure shifts often. Keep one flexible answer in reserve.",
"MSG_LEGENDARY_LIMIT": "Only one of each legendary plant at a time",
"SHOP_LEGEND_THANKS": "{name} joins your garden!",
"QUEST_CLAIM": "Claim", "QUEST_CLAIMED": "Claimed", "QUEST_REWARD": "{n} coins", "QUEST_REWARD_HINT": "recipe hint",
"SHOP_BUY": "Buy · {n}", "SHOP_OWNED": "Owned: {n}", "SHOP_SOLD_OUT": "Sold out", "SHOP_EQUIP": "Equip", "SHOP_EQUIPPED": "Equipped",
"SHOP_THANKS": "Thanks! Come back any time.",
"SETTINGS_FPS": "Frame limit", "SETTINGS_FULLSCREEN": "Fullscreen", "SETTINGS_AUTO_SUN": "Collect sun automatically",
"SETTINGS_DIFFICULTY": "Default difficulty", "SETTINGS_LANGUAGE": "Language",
"SETTINGS_LANGUAGE_NOTE": "Only English is available for now. Other languages are planned.",
"SETTINGS_RESET": "Reset progress", "SETTINGS_RESET_CONFIRM": "Press again to erase everything",
"LANG_EN": "English", "LANG_RU": "Russian", "LANG_ZH_CN": "简体中文", "LANG_JA": "日本語", "LANG_DE": "Deutsch",
}
PLANTS = {
"SUNBUD": ("Sunbud", "Makes 25 sun every 24 seconds. Plant several early."),
"POD_SHOOTER": ("Pod Shooter", "Shoots pods at zombies in its lane."),
"TWIN_POD": ("Twin Pod", "Fires two pods per volley. Also what a Pod Shooter evolves into."),
"BARK_WALL": ("Bark Wall", "A thick stump that zombies have to chew through. Cracks as it weakens."),
"THORN_MINE": ("Thorn Mine", "Cheap. Needs 14 seconds to arm, then bursts under the first zombie that steps on it. Also hits burrowers."),
"EMBER_BERRY": ("Ember Berry", "Explodes a moment after planting, burning everything in a 3×3 area."),
"FROST_MINT": ("Frost Mint", "Its icy pods slow zombies by half, both walking and biting."),
"SNAPPER_TRAP": ("Snapper Trap", "Swallows the zombie in front whole, then chews for 40 seconds. Brutes are too big: it only bites them."),
"BRAMBLE_VINE": ("Bramble Vine", "A thorny tangle. Every bite costs the zombie some health."),
"LANTERN_BLOOM": ("Lantern Bloom", "Its glow makes the 8 surrounding plants work 25% harder."),
"GALE_FERN": ("Gale Fern", "Every few seconds, blows zombies in front of it back by almost a tile."),
"PEPPER_STINGER": ("Pepper Stinger", "Fires a spike that pierces every zombie in the lane. Slow to reload."),
"HIVE_POD": ("Hive Pod", "Releases up to three bees that chase the nearest zombie on any lane. Bees fly over shields."),
"DANDELION_PUFF": ("Dandelion Puff", "Cheap. Puffs seeds at every zombie close by, including neighbouring lanes."),
"TWIN_SUNBUD": ("Twin Sunbud", "Evolved Sunbud. Two flowers, twice the sun."),
"IRONBARK_WALL": ("Ironbark Wall", "Evolved Bark Wall. Twice as tough, and tall enough to stop Hurdlers."),
"GLACIER_SHOOTER": ("Glacier Shooter", "Pod Shooter + Frost Mint. Slows harder and the shot passes through one extra zombie. Fires a bit slower."),
"THORNWALL": ("Thornwall", "Bark Wall + Bramble Vine. Hurts every biter, but isn't tall: Hurdlers still jump it."),
"DAWN_BLOOM": ("Dawn Bloom", "Sunbud + Lantern Bloom. Makes 40 sun and gives neighbours a small boost. As fragile as a flower."),
"VOLCANO_MINE": ("Volcano Mine", "Thorn Mine + Ember Berry. Arms slowly, then erupts in a 3×3 area and leaves burning ground."),
"VORTEX_TRAP": ("Vortex Trap", "Snapper Trap + Gale Fern. Each bite drags zombies from neighbouring lanes into its own."),
"NEEDLE_VOLLEY": ("Needle Volley", "Twin Pod + Pepper Stinger. Bursts of three piercing needles. Long reload."),
"LILY_RAFT": ("Lily Raft", "Floats on pool water. Any lawn plant can be planted on top of it. If that plant is eaten, the raft stays."),
"RIME_LETTUCE": ("Rime Lettuce", "Costs no sun. The first zombie to step on it freezes solid for 10 seconds (Brutes for 5), then stays chilled for a while. Single use."),
"SUN_SOVEREIGN": ("Sun Sovereign", "Legendary. Makes 50 sun every 20 seconds and its corona makes the 8 surrounding plants work 20% harder."),
"PHOENIX_LILY": ("Phoenix Lily", "Legendary. Fires blazing seeds that pass through two zombies and set them alight. Rises from its ashes once when destroyed."),
"STORM_THISTLE": ("Storm Thistle", "Legendary. Calls lightning on the first zombie in its lane; the bolt arcs to four more nearby zombies in any lane and stuns them briefly. Ignores shields."),
"ELDER_OAK": ("Elder Oak", "Legendary. An ancient wall with 9000 health. Thorny bark hurts biters, it regrows when left alone, and it is tall enough to stop Hurdlers."),
}
ZOMBIES = {
"SHAMBLER": ("Shambler", "Walks. Bites. Doesn't stop."),
"FLAGBEARER": ("Flagbearer", "Leads every big wave. A bit quicker than the rest."),
"CONE_HEAD": ("Cone Head", "A traffic cone soaks up the first few hits."),
"BUCKET_HEAD": ("Bucket Head", "A metal bucket makes it roughly five times tougher."),
"SPRINTER": ("Sprinter", "Runs twice as fast. Falls apart just as quickly."),
"HURDLER": ("Hurdler", "Vaults over the first plant with a pole, then walks slowly. Tall plants break the pole."),
"SHIELD_CARRIER": ("Shield Carrier", "Holds a door in front. Shots and thorns hit the door; explosions, area attacks and bees don't."),
"BURROWER": ("Burrower", "Digs under the lawn and surfaces next to the house, then eats its way back. Only mines reach it underground."),
"BRUTE": ("Brute", "Huge, slow, and smashes plants with a log. Too big to swallow or push."),
}
LEVELS = {
"LAWN_01": ("Lawn 1 · First Sprouts", "A few shamblers. Learn sun and shooters."),
"LAWN_02": ("Lawn 2 · Traffic Cones", "Armour appears."),
"LAWN_03": ("Lawn 3 · Flag Day", "The first big waves."),
"LAWN_04": ("Lawn 4 · Quick Feet", "Sprinters join the march."),
"LAWN_05": ("Lawn 5 · Buckets", "Tough heads. Win to unlock grafting."),
"LAWN_06": ("Lawn 6 · Grafting Day", "Try your first hybrid. Win to unlock evolving."),
"LAWN_07": ("Lawn 7 · Over the Fence", "Hurdlers vault your front line."),
"LAWN_08": ("Lawn 8 · Door to Door", "Shield Carriers block your shots."),
"LAWN_09": ("Lawn 9 · Mixed Company", "Everything you've met so far."),
"LAWN_10": ("Lawn 10 · From Below", "Burrowers attack from behind."),
"LAWN_11": ("Lawn 11 · Long Afternoon", "Fourteen waves. Pace your sun."),
"LAWN_12": ("Lawn 12 · Heavy Steps", "Brutes arrive."),
"LAWN_13": ("Lawn 13 · Last Stand", "Sixteen waves of everything. The lawn's final test."),
"LAWN_BONUS_1": ("Sprint Rush", "Fast zombies, short breaks, no grafting."),
"LAWN_BONUS_2": ("Fixed Garden", "Six set seeds, no grafting. Reward: Hive Pod."),
"LAWN_BONUS_3": ("Pure Roots", "Base plants only, fourteen waves."),
"POOL_01": ("Poolside 1 · Blue Morning", "A small pond in mid-lawn. Rafts let you build over it."),
"POOL_02": ("Poolside 2 · High Dive", "Hurdlers test shallow defenses."),
"POOL_03": ("Poolside 3 · Sun Glare", "Shields and sprinters split your attention."),
"POOL_04": ("Poolside 4 · Under the Deck", "Burrowers turn the back line into a front line."),
"POOL_05": ("Poolside 5 · Heavy Weather", "Brutes anchor compact assault groups."),
"POOL_06": ("Poolside 6 · Closing Time", "A long mixed final defense with little room for gaps."),
"POOL_BONUS_1": ("Poolside Bonus · Fast Current", "Short breaks, agile enemies, and no grafting."),
}
QUESTS = {
"FIRST_STEPS": ("First Steps", "Win {n} level."),
"SHAMBLER_HUNTER": ("Shambler Hunter", "Defeat {n} Shamblers."),
"CONE_CRACKER": ("Cone Cracker", "Defeat {n} Cone Heads."),
"FIRST_GRAFT": ("Green Thumb", "Graft {n} hybrid."),
"EVOLVER": ("Next Tier", "Evolve plants {n} times."),
"CLEAN_LAWN": ("Not a Scratch", "Win {n} levels without using a mower."),
"BUCKET_LIST": ("Bucket List", "Defeat {n} Bucket Heads."),
"SUN_HOARDER": ("Sun Hoarder", "Collect {n} sun in total."),
"GARDENER": ("Gardener", "Plant {n} plants."),
"RECIPE_BOOK": ("Recipe Book", "Discover {n} different grafts."),
"HARD_SOIL": ("Hard Soil", "Win {n} level on Hard or Hard+."),
"GIANT_SLAYER": ("Giant Slayer", "Defeat {n} Brutes."),
}
SHOP = {
"EXTRA_SLOT": ("Seed Slot", "One more seed in every level (up to 10)."),
"START_SUN": ("Morning Dew", "+25 sun at the start of every level."),
"MOWER_KIT": ("Mower Repair Kit", "Single use. Rebuilds a spent mower during a level."),
"RECIPE_HINT": ("Recipe Hint", "Reveals the two ingredients of an unknown graft."),
"SKIN_AZURE": ("Azure Mower", "Cosmetic. A blue paint job for your mowers."),
"SKIN_MOSS": ("Moss Mower", "Cosmetic. Green, to blend in with the lawn."),
"SKIN_GOLD": ("Gold Mower", "Cosmetic. Purely for showing off."),
"LEGEND_SUN_SOVEREIGN": ("Sun Sovereign", "Legendary seed. A crowned sunflower that fuels and empowers its neighbours."),
"LEGEND_PHOENIX_LILY": ("Phoenix Lily", "Legendary seed. Burning, piercing shots, and it comes back once."),
"LEGEND_STORM_THISTLE": ("Storm Thistle", "Legendary seed. Chain lightning across lanes. Also a reward for clearing Pool 6."),
"LEGEND_ELDER_OAK": ("Elder Oak", "Legendary seed. A self-healing ancient wall. Also a reward for clearing Lawn 13."),
}
for k, (n, d) in PLANTS.items(): S[f"PLANT_{k}_NAME"] = n; S[f"PLANT_{k}_DESC"] = d
for k, (n, d) in ZOMBIES.items(): S[f"ZOMBIE_{k}_NAME"] = n; S[f"ZOMBIE_{k}_DESC"] = d
for k, (n, d) in LEVELS.items(): S[f"LEVEL_{k}_NAME"] = n; S[f"LEVEL_{k}_DESC"] = d
for k, (n, d) in QUESTS.items(): S[f"QUEST_{k}_TITLE"] = n; S[f"QUEST_{k}_DESC"] = d
for k, (n, d) in SHOP.items(): S[f"SHOP_{k}_NAME"] = n; S[f"SHOP_{k}_DESC"] = d
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(root, "localization", "translations.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["keys", "en", "ru", "zh_CN", "ja", "de"])
    for k in sorted(S):
        w.writerow([k, S[k], "", "", "", ""])
print(len(S), "keys")
